/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei/native';

export default function Horse(props: any) {
  const group = useRef(null);
  const { nodes, materials } = useGLTF(require('./Horse.glb'));

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Horse" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Horse_1"
              geometry={nodes.Horse_1.geometry}
              material={materials.Main}
              skeleton={nodes.Horse_1.skeleton}
            />
            <skinnedMesh
              name="Horse_2"
              geometry={nodes.Horse_2.geometry}
              material={materials.Hair}
              skeleton={nodes.Horse_2.skeleton}
            />
            <skinnedMesh
              name="Horse_3"
              geometry={nodes.Horse_3.geometry}
              material={materials.Main_Dark}
              skeleton={nodes.Horse_3.skeleton}
            />
            <skinnedMesh
              name="Horse_4"
              geometry={nodes.Horse_4.geometry}
              material={materials.Muzzle}
              skeleton={nodes.Horse_4.skeleton}
            />
            <skinnedMesh
              name="Horse_5"
              geometry={nodes.Horse_5.geometry}
              material={materials.Hooves}
              skeleton={nodes.Horse_5.skeleton}
            />
            <skinnedMesh
              name="Horse_6"
              geometry={nodes.Horse_6.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Horse_6.skeleton}
            />
            <skinnedMesh
              name="Horse_7"
              geometry={nodes.Horse_7.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Horse_7.skeleton}
            />
            <skinnedMesh
              name="Horse_8"
              geometry={nodes.Horse_8.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Horse_8.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
